app = "icecastserver" # cambia por el nombre real de tu app en Fly.io

[build]

[[services]]
  internal_port = 8000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
